# -*- coding: utf-8 -*-
"""Financeiro - Detector de Fraudes fiscais

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17y9UQC4-XDfITLBXw-zzj_uvL_yLczpl
"""

# Importa as bibliotecas necessárias
import pandas as pd
from io import StringIO
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import recall_score, classification_report

# String que contém os dados da tabela
dados_fraude_str = """
ID,Valor_Transacao,Idade_Conta,Local_Risco,Hora_Dia,Fraude
T01,50.00,12,1,10,0
T02,1200.00,36,3,14,0
T03,500.00,5,5,2,1
T04,25.00,60,1,18,0
T05,800.00,24,2,11,0
T06,15.00,8,1,9,0
T07,3000.00,48,4,23,1
T08,90.00,18,1,17,0
T09,400.00,12,2,13,0
T10,150.00,30,1,8,0
T11,20.00,72,1,16,0
T12,600.00,6,5,3,1
T13,100.00,20,2,15,0
T14,180.00,40,1,12,0
T15,30.00,10,1,19,0
T16,700.00,50,3,20,0
T17,45.00,15,1,7,0
T18,1000.00,25,2,21,0
T19,65.00,35,1,9,0
T20,200.00,45,1,13,0
"""

# Cria o DataFrame
df_fraude = pd.read_csv(StringIO(dados_fraude_str))

# Exibe a contagem para confirmar o desequilíbrio (0s e 1s)
print("--- Contagem da Variável Fraude ---")
print(df_fraude['Fraude'].value_counts())

print("\nDataFrame de Fraudes Criado com Sucesso!")
print(df_fraude.head())

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Define Features (X) e Target (y)
X = df_fraude.drop(['ID', 'Fraude'], axis=1)
y = df_fraude['Fraude']

# Divide os dados em treino e teste (70%/30%), garantindo que a proporção de Fraudes seja mantida.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

# Instancia e treina o modelo de Regressão Logística
model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

print("Separação de dados e Treinamento do Modelo Base concluídos.")

from sklearn.metrics import recall_score, classification_report, confusion_matrix

# Faz previsões no conjunto de teste
y_pred = model.predict(X_test)

# Gera a Matriz de Confusão
matriz_confusao = confusion_matrix(y_test, y_pred)
print("\n--- Matriz de Confusão ---")
print(matriz_confusao)

# Gera o Relatório de Classificação
relatorio = classification_report(y_test, y_pred, zero_division=0)
print("\n--- Relatório de Classificação ---")
print(relatorio)

# Calcula o Recall especificamente para a classe de Fraude (1)
recall_fraude = recall_score(y_test, y_pred, pos_label=1)
print(f"\nRecall para Fraude (Classe 1): {recall_fraude:.2f}")

import pandas as pd

# Novo projeto (Caso A: Suspeito, Caso B: Normal)
novas_transacoes = pd.DataFrame({
    'Valor_Transacao': [3500.00, 150.00],
    'Idade_Conta': [8, 55],
    'Local_Risco': [5, 1],
    'Hora_Dia': [1, 15]
})

print("--- Novas Transações Criadas (Aguardando Previsão) ---")
print(novas_transacoes)

# Faz a previsão da probabilidade de fraude (Classe 1)
previsoes_proba = model.predict_proba(novas_transacoes)

# Cria um novo DataFrame para organizar os resultados
resultados = novas_transacoes.copy()
resultados['Probabilidade_Fraude'] = previsoes_proba[:, 1]
resultados['Previsao_Classe'] = model.predict(novas_transacoes)

print("\n--- Resultado da Análise do Modelo ---")
print("Previsao_Classe: 1 = Fraude, 0 = Normal")
print(resultados)